#!/bin/bash
#
#  Device Database
# Format: [HWID]="deviceDescription|CPU|device override|flags|"
# Flags: isCbox, hasLAN, kbl_rwl18, adl_fixed_rwl, noUEFI
#

# Declare the device database
declare -gA DEVICE_DB

# Populate the database
DEVICE_DB=(
	# SNB devices (EOL) - Intel SandyBridge
	["BUTTERFLY*"]="HP Pavilion Chromebook 14|SNB|||"
	["LUMPY*"]="Samsung Chromebook Series 5 550|SNB|||"
	["PARROT*"]="Acer C7/C710 Chromebook|SNB|||"
	["STUMPY*"]="Samsung Chromebox Series 3|SNB||isCbox,hasLAN|"

	# IVB devices (EOL) - Intel IvyBridge
	["LINK*"]="Google Chromebook Pixel 2013|IVB|||"
	["STOUT*"]="Lenovo Thinkpad X131e Chromebook|IVB|||"

	# HSW devices (EOL) - Intel Haswell
	["FALCO*"]="HP Chromebook 14|HSW|||"
	["LEON*"]="Toshiba CB30/CB35 Chromebook|HSW|||"
	["MCCLOUD*"]="Acer Chromebox CXI|HSW||isCbox,hasLAN|"
	["MONROE*"]="LG Chromebase|HSW||hasLAN|"
	["PANTHER*"]="ASUS Chromebox CN60|HSW||isCbox,hasLAN|"
	["PEPPY*"]="Acer C720/C720P Chromebook|HSW|||"
	["TRICKY*"]="Dell Chromebox 3010|HSW||isCbox,hasLAN|"
	["WOLF*"]="Dell Chromebook 11|HSW|||"
	["ZAKO*"]="HP Chromebox CB1|HSW||isCbox,hasLAN|"

	# BDW devices (EOL) - Intel Broadwell
	["AURON_PAINE*"]="Acer Chromebook 11 (C740)|BDW|||"
	["AURON_YUNA*"]="Acer Chromebook 15 (CB5-571, C910)|BDW|||"
	["BUDDY*"]="Acer Chromebase 24|BDW||hasLAN|"
	["GANDOF*"]="Toshiba Chromebook 2 (2015) CB30/CB35|BDW|||"
	["GUADO*"]="ASUS Chromebox 2 / CN62|BDW||isCbox,hasLAN|"
	["LULU*"]="Dell Chromebook 13 (7310)|BDW|||"
	["RIKKU*"]="Acer Chromebox CXI2|BDW||isCbox,hasLAN|"
	["SAMUS*"]="Google Chromebook Pixel 2015|BDW|||"
	["TIDUS*"]="Lenovo ThinkCentre Chromebox|BDW||isCbox,hasLAN|"

	# BYT devices (EOL) - Intel BayTrail
	["BANJO*"]="Acer Chromebook 15 (CB3-531)|BYT|||"
	["CANDY*"]="Dell Chromebook 11|BYT|||"
	["CLAPPER*"]="Lenovo N20/N20P Chromebook|BYT|||"
	["ENGUARDE*"]="(multiple device matches)|BYT|||"
	["ENGUARDE_???-???-??A*"]="CTL N6 Education Chromebook|BYT|||"
	["ENGUARDE_???-???-??B*"]="M&A Chromebook|BYT|||"
	["ENGUARDE_???-???-??C*"]="Senkatel C1101 Chromebook|BYT|||"
	["ENGUARDE_???-???-??D*"]="Edxis Education Chromebook|BYT|||"
	["ENGUARDE_???-???-??E*"]="Lenovo N21 Chromebook|BYT|||"
	["ENGUARDE_???-???-??F*"]="RGS Education Chromebook|BYT|||"
	["ENGUARDE_???-???-??G*"]="Crambo Chromebook|BYT|||"
	["ENGUARDE_???-???-??H*"]="True IDC Chromebook|BYT|||"
	["ENGUARDE_???-???-??I*"]="Videonet Chromebook|BYT|||"
	["ENGUARDE_???-???-??J*"]="eduGear Chromebook R|BYT|||"
	["ENGUARDE_???-???-??K*"]="ASI Chromebook|BYT|||"
	["GLIMMER*"]="Lenovo ThinkPad 11e/Yoga Chromebook|BYT|||"
	["GNAWTY*"]="Acer Chromebook 11 (CB3-111/131,C730/C730E/C735)|BYT|||"
	["HELI*"]="Haier Chromebook G2|BYT|||"
	["KIP*"]="HP Chromebook 11 G3/G4, 14 G4|BYT|||"
	["NINJA*"]="AOpen Chromebox Commercial|BYT||isCbox,hasLAN|"
	["ORCO*"]="Lenovo Ideapad 100S Chromebook|BYT|||"
	["QUAWKS*"]="ASUS Chromebook C300|BYT|||"
	["SQUAWKS*"]="ASUS Chromebook C200|BYT|||"
	["SUMO*"]="AOpen Chromebase Commercial|BYT|||"
	["SWANKY*"]="Toshiba Chromebook 2 (2014) CB30/CB35|BYT|||"
	["WINKY*"]="Samsung Chromebook 2 (XE500C12)|BYT|||"

	# BSW devices (EOL) - Intel Braswell
	["BANON*"]="Acer Chromebook 15 (CB3-532)|BSW|||"
	["CELES*"]="Samsung Chromebook 3|BSW|||"
	["CYAN*"]="Acer Chromebook R11 (C738T)|BSW|||"
	["EDGAR*"]="Acer Chromebook 14 (CB3-431)|BSW|||"
	["KEFKA*"]="Dell Chromebook 11 (3180,3189)|BSW|||"
	["REKS*"]="REKS BSW Chromebook|BSW|||"
	["REKS_???-???-???-*"]="Lenovo N22 Chromebook|BSW|||"
	["REKS_???-???-???-B*"]="Lenovo N42 Chromebook|BSW|||"
	["REKS_???-???-???-C*"]="Lenovo N23 Chromebook (Touch)|BSW|||"
	["REKS_???-???-???-D*"]="Lenovo N23 Chromebook|BSW|||"
	["RELM*"]="(unknown RELM)|BSW|||"
	["RELM_???-B*"]="CTL NL61 Chromebook|BSW|||"
	["RELM_???-C*"]="Edxis Education Chromebook|BSW|||"
	["RELM_???-F*"]="Mecer V2 Chromebook|BSW|||"
	["RELM_???-G*"]="HP Chromebook 11 G5 EE|BSW|||"
	["RELM_???-H*"]="Acer Chromebook 11 N7 (C731)|BSW|||"
	["RELM_???-Z*"]="Quanta OEM Chromebook|BSW|||"
	["SETZER*"]="HP Chromebook 11 G5|BSW|||"
	["TERRA*"]="ASUS Chromebook C202SA, C300SA/C301SA|BSW|||"
	["TERRA_???-???-???-A*"]="ASUS Chromebook C202SA|BSW|||"
	["TERRA_???-???-???-B*"]="ASUS Chromebook C300SA/C301SA|BSW|||"
	["ULTIMA*"]="Lenovo ThinkPad 11e/Yoga Chromebook (G3)|BSW|||"
	["WIZPIG*"]="Wizpig BSW Chromebook|BSW|||"
	["WIZPIG_???-???-??A*"]="CTL Chromebook J5|BSW|||"
	["WIZPIG_???-???-??B*"]="Edugear CMT Chromebook|BSW|||"
	["WIZPIG_???-???-??C*"]="Haier Convertible Chromebook 11 C|BSW|||"
	["WIZPIG_???-???-??D*"]="Viglen Chromebook 360|BSW|||"
	["WIZPIG_???-???-??G*"]="Prowise ProLine Chromebook|BSW|||"
	["WIZPIG_???-???-??H*"]="PCMerge Chromebook PCM-116T-432B|BSW|||"
	["WIZPIG_???-???-??I*"]="Multilaser M11C Chromebook|BSW|||"

	# SKL devices (EOL) - Intel Skylake
	["ASUKA*"]="Dell Chromebook 13 (3380)|SKL|||"
	["CAROLINE*"]="Samsung Chromebook Pro|SKL|||"
	["CAVE*"]="ASUS Chromebook Flip C302|SKL|||"
	["CHELL*"]="HP Chromebook 13 G1|SKL|||"
	["LARS*"]="Acer Chromebook 14 for Work|SKL|||"
	["LARS_???-???-???-?3?*"]="Acer Chromebook 11 (C771, C771T)|SKL|||"
	["LILI*"]="Acer Chromebook R13 (CB5-312T)|SKL|||"
	["SENTRY*"]="Lenovo Thinkpad 13 Chromebook|SKL|||"

	# APL devices - Intel ApolloLake
	["ASTRONAUT*"]="Acer Chromebook 11 (C732*)|APL|||"
	["BABYMEGA*"]="Asus Chromebook C223NA|APL|||"
	["BABYTIGER*"]="Asus Chromebook C523NA|APL|||"
	["BLACKTIP*"]="White Label Chrombook|APL|blacktip||"
	["BLUE*"]="Acer Chromebook 15 [CB315-1H*]|APL|||"
	["BRUCE*"]="Acer Chromebook Spin 15 [CP315]|APL|||"
	["CORAL*"]="Incorrectly identified APL Chromebook|APL|||"
	["ELECTRO*"]="Acer Chromebook Spin 11 (R751T)|APL|||"
	["EPAULETTE*"]="UNK Acer Chromebook|APL|||"
	["LAVA*"]="Acer Chromebook Spin 11 CP311|APL|||"
	["NASHER*"]="Dell Chromebook 11 5190|APL|||"
	["NASHER360*"]="Dell Chromebook 11 2-in-1 5190|APL|||"
	["PYRO*"]="Lenovo Thinkpad 11e/Yoga Chromebook (G4)|APL|||"
	["RABBID*"]="ASUS Chromebook C423/CX1400|APL|||"
	["REEF*"]="ASUS Chromebook C213NA|APL|||"
	["REEF_???-B*"]="Acer Chromebook Spin 11 (R751T)|APL|electro||"
	["ROBO*"]="Lenovo 100e Chromebook|APL|||"
	["ROBO360*"]="Lenovo 500e Chromebook|APL|||"
	["SAND*"]="Acer Chromebook 15 (CB515-1HT)|APL|||"
	["SANTA*"]="Acer Chromebook 11 (CB311-8H)|APL|||"
	["SNAPPY*"]="HP Chromebook x360 11 G1/11 G6/14 G5|APL|||"
	["SNAPPY_???-A*"]="HP Chromebook x360 11 G1 EE|APL|||"
	["SNAPPY_???-B*"]="HP Chromebook 11 G6 EE|APL|||"
	["SNAPPY_???-C*"]="HP Chromebook 14 G5|APL|||"
	["WHITETIP*"]="CTL Chromebook J41/J41T|APL|||"

	# KBL devices - Intel KabyLake
	["AKALI*"]="Acer Chromebook 13 / Spin 13|KBL|nami||"
	["ATLAS*"]="Google Pixelbook Go|KBL||kbl_rwl18|"
	["BARD*"]="Acer Chromebook 715 (CB715)|KBL|nami||"
	["BLEEMO*"]="Asus Chromebox 3 / CN65 (Core i7)|KBL|fizz|isCbox,hasLAN|"
	["EKKO*"]="Acer Chromebook 714 (CB714)|KBL|nami||"
	["ENDEAVOUR*"]="Google Meet Series One|KBL||isCbox,kbl_rwl18|"
	["EVE*"]="Google Pixelbook|KBL|||"
	["EXCELSIOR*"]="Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["EXCELSIOR-OOLH*"]="CTL Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["EXCELSIOR-URAR*"]="Asus Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["FIZZ"]="TBD KBL Chromebox|KBL||isCbox,hasLAN|"
	["JAX*"]="AOpen Chromebox Commercial 2|KBL|fizz|isCbox,hasLAN|"
	["KARMA*"]="Acer Chromebase 24I2|KBL||kbl_rwl18|"
	["KENCH*"]="HP Chromebox G2|KBL|fizz|isCbox,hasLAN|"
	["LEONA*"]="Asus Chromebook C425TA|KBL||kbl_rwl18|"
	["NAMI*"]="NAMI Chromebook (multi)|KBL|nami||"
	["NAUTILUS*"]="Samsung Chromebook Plus V2|KBL|||"
	["NOCTURNE*"]="Google Pixel Slate|KBL||kbl_rwl18|"
	["PANTHEON*"]="Lenovo Yoga Chromebook C630|KBL|nami||"
	["RAMMUS*"]="Asus Chromebook C425/C433/C434|KBL|||"
	["SHYVANA*"]="Asus Chromebook Flip C433/C434|KBL||kbl_rwl18|"
	["SION*"]="Acer Chromebox CXI3|KBL|fizz|isCbox,hasLAN|"
	["SONA*"]="HP Chromebook x360 14|KBL|nami||"
	["SORAKA*"]="HP Chromebook x2|KBL|||"
	["SYNDRA*"]="HP Chromebook 15 G1|KBL|nami||"
	["TEEMO*"]="Asus Chromebox 3 / CN65|KBL|fizz|isCbox,hasLAN|"
	["VAYNE*"]="Dell Inspiron Chromebook 14 (7486)|KBL|nami||"
	["WUKONG*"]="CTL Chromebox CBx1|KBL|fizz|isCbox,hasLAN|"
	["WUKONG_???-???-???-??C*"]="ViewSonic NMP660 Chromebox|KBL|fizz|isCbox,hasLAN|"

	# GLK devices - Intel GeminiLake
	["AMPTON*"]="Asus Chromebook Flip C214/C234|GLK|||"
	["APEL*"]="Asus Chromebook Flip C204|GLK|||"
	["APELE*"]="Asus Chromebook CX1101CMA|GLK|apel||"
	["BLOOG*"]="HP Chromebook x360 12b|GLK|||"
	["BLOOGLET*"]="HP Chromebook 14a|GLK|||"
	["BLOOGUARD*"]="HP Chromebook x360 14a/14b|GLK|||"
	["BLORB*"]="Acer Chromebook 315|GLK|||"
	["BLUEBIRD*"]="Samsung Chromebook 4|GLK|||"
	["BOBBA*"]="Acer Chromebook 311|GLK|||"
	["BOBBA360*"]="Acer Chromebook Spin 311/511|GLK|||"
	["CASTA*"]="Samsung Chromebook 4+|GLK|||"
	["DOOD*"]="NEC Chromebook Y2|GLK|||"
	["DORP*"]="HP Chromebook 14 G6|GLK|||"
	["DROID*"]="Acer Chromebook 314|GLK|||"
	["FLEEX*"]="Dell Chromebook 3100|GLK|||"
	["FOOB*"]="CTL Chromebook VX11/VT11T|GLK|||"
	["GARFOUR*"]="CTL Chromebook NL81/NL81T|GLK|||"
	["GARG*"]="CTL Chromebook NL71/CT/LTE|GLK|||"
	["GARG360*"]="CTL Chromebook NL71T/TW/TWB|GLK|||"
	["GLK*"]="Acer Chromebook 311|GLK|||"
	["GLK360*"]="Acer Chromebook Spin 311|GLK|||"
	["GRABBITER*"]="Dell Chromebook 3100 2-in-1|GLK|||"
	["LASER*"]="Lenovo Chromebook C340|GLK|||"
	["LASER14*"]="Lenovo Chromebook S340 / IdeaPad 3|GLK|||"
	["LICK*"]="Lenovo Ideapad 3 Chromebook|GLK|||"
	["MEEP*"]="HP Chromebook x360 11 G2 EE|GLK|||"
	["MIMROCK*"]="HP Chromebook 11 G7 EE|GLK|||"
	["NOSPIKE*"]="ASUS Chromebook C424|GLK|||"
	["ORBATRIX*"]="Dell Chromebook 3400|GLK|||"
	["PHASER*"]="Lenovo 100e Chromebook 2nd Gen|GLK|||"
	["PHASER360*"]="Lenovo 300e/500e Chromebook 2nd Gen|GLK|||"
	["SPARKY*"]="Acer Chromebook 512 (C851/C851T)|GLK|||"
	["SPARKY360*"]="Acer Chromebook Spin 512 (R851TN)|GLK|||"
	["VORTICON*"]="HP Chromebook 11 G8 EE|GLK|||"
	["VORTININJA*"]="HP Chromebook x360 11 G3 EE|GLK|||"

	# WHL devices - Intel WhiskeyLake
	["ARCADA*"]="Dell Latitude 5300|WHL|sarien|noUEFI|"
	["SARIEN*"]="Dell Latitude 5400|WHL||noUEFI|"

	# CML devices - Intel CometLake
	# Hatch baseboard
	["AKEMI*"]="Lenovo Ideapad Flex 5 Chromebook|CML|||"
	["DRAGONAIR*"]="HP Chromebook x360 14c|CML|||"
	["DRATINI*"]="HP Pro c640 Chromebook|CML|||"
	["HATCH*"]="Acer Chromebook Spin 713 (CP713-2W)|CML|||"
	["HELIOS*"]="ASUS Chromebook Flip C436FA|CML|||"
	["JINLON*"]="HP Elite c1030 Chromebook / HP Chromebook x360 13c|CML|||"
	["KINDRED*"]="Acer Chromebook 712 (C871)|CML|||"
	["KLED*"]="Acer Chromebook Spin 713 (CP713-2W)|CML|||"
	["KOHAKU*"]="Samsung Galaxy Chromebook|CML|||"
	["NIGHTFURY*"]="Samsung Galaxy Chromebook 2|CML|||"
	# Puff baseboard
	["AMBASSADOR*"]="CTL Meet Compute System GQE15C|CML||isCbox,hasLAN|"
	["DOOLY*"]="HP Chromebase 21.5|CML||isCbox,hasLAN|"
	["DUFFY*"]="ASUS Chromebox 4|CML||isCbox,hasLAN|"
	["FAFFY*"]="ASUS Fanless Chromebox|CML||isCbox,hasLAN|"
	["GENESIS*"]="Google Meet Series One|CML||isCbox,hasLAN|"
	["KAISA*"]="Acer Chromebox CXI4|CML||isCbox,hasLAN|"
	["MOONBUGGY*"]="Avocor Series One Board 65|CML||isCbox,hasLAN|"
	["NOIBAT*"]="HP Chromebox G3|CML||isCbox,hasLAN|"
	["PUFF*"]="Puff CML Chromebox|CML||isCbox,hasLAN|"
	["SCOUT*"]="Avocor Series One Desk 27|CML||isCbox,hasLAN|"
	["WYVERN*"]="CTL Chromebox CBx2|CML||isCbox,hasLAN|"
	# Drallion baseboard
	["DRALLION*"]="Dell Latitude 7410 Chromebook Enterprise|CML|drallion||"


	# JSL devices - Intel JasperLake
	["AWADORON-UKVH*"]="ASUS CX1505CKA/CB1505CKA|JSL|||"
	["AWASUKI-AJPW*"]="ASUS CX1405CKA/CB1405CKA|JSL|||"
	["BEADRIX*"]="Beadrix JSL Chromebook|JSL|||"
	["BEADRIX-GPPJ*"]="DINATECH Gen1 Chromebook SG20JL1C|JSL|||"
	["BEADRIX-RIJZ*"]="Multilaser Chromebook M11C-PC919|JSL|||"
	["BEADRIX-ULGS*"]="Evolve III Chromebook 11 E1|JSL|||"
	["BEADRIX-XEER*"]="Positivo Chromebook N2320|JSL|||"
	["BEADRIX-XYBG*"]="Allied Chromebook 11 N5100EO-864180|JSL|||"
	["BEETLEY*"]="Lenovo Flex 3i/3i-15 Chromebook|JSL|||"
	["BLIPPER*"]="Lenovo 3i-15 Chromebook|JSL|||"
	["BOOKEM*"]="Lenovo 100e Chromebook Gen 3|JSL|||"
	["BOTEN*"]="Lenovo 500e Chromebook Gen 3|JSL|||"
	["BOTENFLEX*"]="Lenovo Flex 3i/3i-11 Chromebook|JSL|||"
	["BOXY*"]="Lenovo Chromebox Micro|JSL||isCbox,hasLAN|"
	["BUGZZY*"]="Samsung Galaxy Chromebook 2 360|JSL|||"
	["CRET*"]="Dell Chromebook 3110|JSL|||"
	["CRET360*"]="Dell Chromebook 3110 2-in-1|JSL|||"
	["DEXI*"]="AOPEN Chromebox Mini 2|JSL||isCbox,hasLAN|"
	["DITA-*"]="Acer Chromebox Mini CXM1|JSL||isCbox,hasLAN|"
	["DITA-AZYL*"]="AOPEN Chromebox P1|JSL||isCbox,hasLAN|"
	["DRAWCIA*"]="HP Chromebook x360 11 G4 EE|JSL|||"
	["DRAWLAT*"]="HP Chromebook 11 G9 EE|JSL|||"
	["DRAWMAN*"]="HP Chromebook 14 G7|JSL|||"
	["DRAWPER*"]="HP Fortis 14 G10 Chromebook|JSL|||"
	["GALITH*"]="ASUS Chromebook CX1500CKA|JSL|||"
	["GALITH360*"]="ASUS Chromebook CX1500FKA|JSL|||"
	["GALLOP*"]="ASUS Chromebook CX1700CKA|JSL|||"
	["GALNAT*"]="ASUS Chromebook CX1102|JSL|||"
	["GALNAT360*"]="ASUS Chromebook Flip CX1102|JSL|||"
	["GALTIC*"]="ASUS Chromebook CX1|JSL|||"
	["GALTIC360*"]="ASUS Chromebook CX1400FKA|JSL|||"
	["KRACKO*"]="CTL Chromebook NL72|JSL|||"
	["KRACKO360*"]="LG Chromebook 11TC50Q/11TQ50Q|JSL|||"
	["KRACKO360-BLXA*"]="CTL Chromebook NL72T|JSL|||"
	["LANDIA*"]="HP Chromebook x360 14a|JSL|||"
	["LANDRID*"]="HP Chromebook 15a|JSL|||"
	["LANTIS*"]="HP Chromebook 14a|JSL|||"
	["MADOO*"]="HP Chromebook x360 14b|JSL|||"
	["MAGISTER*"]="Acer Chromebook Spin 314|JSL|||"
	["MAGLET*"]="Acer Chromebook 512 (C852)|JSL|||"
	["MAGLIA*"]="Acer Chromebook Spin 512|JSL|||"
	["MAGLITH*"]="Acer Chromebook 511|JSL|||"
	["MAGMA*"]="Acer Chromebook 315|JSL|||"
	["MAGNETO*"]="Acer Chromebook 314|JSL|||"
	["MAGNETO-SGGB*"]="Packard Bell Chromebook 314|JSL|||"
	["MAGOLOR*"]="Acer Chromebook Spin 511 [R753T]|JSL|||"
	["MAGPIE*"]="Acer Chromebook 317 [CB317-1H]|JSL|||"
	["METAKNIGHT*"]="NEC Chromebook Y3|JSL|||"
	["PALUTENA-TQFG*"]="Gateway Chromebook 314|JSL|||"
	["PALUTENA-YVYF*"]="Acer Chromebook 314|JSL|||"
	["PASARA*"]="Gateway Chromebook 15|JSL|||"
	["PEEZER*"]="Peezer JSL Chromebook|JSL|||"
	["PEEZER-EUBP*"]="Multilaser Chromebook M11C-PC924|JSL|||"
	["PEEZER-FYEL*"]="CTL Chromebook PX11EG|JSL|||"
	["PEEZER-LXVK*"]="Acer Chromebook 311(CO731)|JSL|||"
	["PEEZER-PKZD*"]="Edxis E-Lite Chromebook 11|JSL|||"
	["PEEZER-UGDD*"]="CA11J2|JSL|||"
	["PIRETTE*"]="Pirette JSL Chromebook|JSL|||"
	["PIRETTE-LLJI*"]="Axioo Chromebook P11|JSL|||"
	["PIRETTE-NGVJ*"]="SPC Chromebook Z1 Mini|JSL|||"
	["PIRETTE-RVKU*"]="CTL Chromebook PX11E|JSL|||"
	["PIRETTE-UBKE*"]="Zyrex Chromebook M432-2|JSL|||"
	["PIRIKA*"]="Pirika JSL Chromebook|JSL|||"
	["PIRIKA-BMAD*"]="CTL Chromebook PX14E/PX14EX/PX14EXT|JSL|||"
	["PIRIKA-NPXS*"]="Axioo Chromebook P14|JSL|||"
	["PIRIKA-XAJY*"]="Gateway Chromebook 14|JSL|||"
	["SASUKE*"]="Samsung Galaxy Chromebook Go|JSL|||"
	["SASUKETTE*"]="Samsung Galaxy Chromebook Go 11|JSL|||"
	["STORO*"]="ASUS Chromebook CR1100CKA|JSL|||"
	["STORO360*"]="ASUS Chromebook Flip CR1100FKA|JSL|||"
	["TARANZA-RPOG*"]="ASUS Fanless Chromebox CF40|JSL||isCbox,hasLAN|"

	# TGL devices - Intel TigerLake
	["CHRONICLER*"]="FMV Chromebook 14F|TGL|||"
	["COLLIS*"]="AAsus Chromebook Flip CX3|TGL|||"
	["COPANO*"]="Asus Chromebook Flip CX5 (CX5400)|TGL|||"
	["DELBIN*"]="ASUS Chromebook Flip CX55/CX5500/C536|TGL|||"
	["DROBIT*"]="ASUS Chromebook CX9 (CX9400)|TGL|||"
	["ELDRID*"]="HP Chromebook x360 14c|TGL|||"
	["ELEMI*"]="HP Pro c640 G2 Chromebook|TGL|||"
	["LILLIPUP*"]="Lenovo IdeaPad Flex 5i Chromebook|TGL|||"
	["LINDAR*"]="Lenovo Slim 5/5i/Flex 5i Chromebook|TGL|||"
	["LINDAR-EDFZ*"]="Lenovo 5i-14 Chromebook|TGL|||"
	["LINDAR-LCDF*"]="Lenovo Slim 5 Chromebook|TGL|||"
	["VOEMA*"]="Acer Chromebook Spin 514 (CB514-2H)|TGL|||"
	["VOLET*"]="Acer Chromebook 515 (CB515-1W, CB515-1WT)|TGL|||"
	["VOLTA*"]="Acer Chromebook 514 (CB514-1W, CB514-1WT)|TGL|||"
	["VOXEL*"]="Acer Chromebook Spin 713 (CP713-3W)|TGL|||"

	# ADL devices - Intel AlderLake/RaptorLake-U/P
	["ANAHERA*"]="HP Elite c640 14 inch G3 Chromebook|ADL|||"
	["AURASH"]="AOpen Chromebox Commercial 3|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BANSHEE*"]="Framework Chromebook|ADL||adl_fixed_rwl|"
	["CONSTITUTION*"]="Google Meet Series Two|ADL||adl_fixed_rwl|"
	["CROTA*"]="Dell Latitude 5430 Chromebook|ADL|||"
	["CROTA360*"]="Dell Latitude 5430 2-in-1 Chromebook|ADL|||"
	["DOCHI*"]="Acer Chromebook Plus Spin 514 [CP514-4HN]|ADL|||"
	["FELWINTER*"]="ASUS Chromebook Flip CX5(CX5601)|ADL|||"
	["GIMBLE*"]="HP Chromebook x360 14c-cd0|ADL||adl_fixed_rwl|"
	["GLADIOS*"]="HP Chromebox Enterprise G4|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["INTREPID*"]="CTL Meet Compute System GQE20C|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["KANO*"]="Acer Chromebook Spin 714 [CP714-1WN]|ADL|||"
	["KINOX*"]="Lenovo ThinkCentre M60q Chromebox|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["KULDAX*"]="ASUS Chromebox 5 [CN67]|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON*"]="CTL Chromebox CBx3|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["MARASOV*"]="ASUS Chromebook CX34|ADL||adl_fixed_rwl|"
	["MITHRAX*"]="ASUS Chromebook CX34 Flip (CX3401)|ADL|||"
	["MITHRAX-ISVS*"]="Asus Chromebook Vibe CX34 Flip (CX3401)|ADL|||"
	["MOLI*"]="Acer Chromebox CXI5|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["OMNIGUL*"]="Acer Chromebook Plus 515 [CB515-2H]|ADL||adl_fixed_rwl|"
	["OMNIKNIGHT*"]="Acer Chromebook Plus Enterprise 515|ADL|||"
	["OSIRIS*"]="Acer Chromebook 516 GE [CBG516-1H]|ADL||adl_fixed_rwl|"
	["PRIMUS*"]="Lenovo ThinkPad C14 Gen 1 Chromebook|ADL|||"
	["REDRIX*"]="HP Elite Dragonfly Chromebook|ADL||adl_fixed_rwl|"
	["REDRIX4ES*"]="HP Elite Dragonfly Chromebook Ent|ADL|||"
	["TANIKS*"]="Lenovo IdeaPad Gaming Chromebook 16|ADL|||"
	["VELL*"]="HP Dragonfly Pro Chromebook|ADL|||"
	["VOLMAR*"]="Acer Chromebook Vero 514|ADL|||"
	["ZAVALA*"]="Acer Chromebook Vero 712|ADL|||"
	["TAEKO*"]="Lenovo Lenovo Flex 5i Chromebook 14\"|ADL|||"
	["TARLO*"]="Lenovo 5i Chromebook 16\"|ADL|||"

	# ADN devices - Intel AlderLake-N
	["ANRAGGAR*"]="ASUS Chromebook CR12|ADN|||"
	["ANRAGGAR360*"]="ASUS Chromebook CR12 flip|ADN|||"
	["CRAASK*"]="Acer Chromebook Spin 512|ADN|||"
	["CRAASKANA*"]="Acer Chromebook 311|ADN|||"
	["CRAASKBOWL*"]="Acer Chromebook Spin 511|ADN|||"
	["CRAASKINO*"]="Acer Chromebook 315|ADN|||"
	["CRAASKOV*"]="Acer Chromebook Spin 312 (CP312-1H, CP312-1HN)|ADN|||"
	["CRAASKVIN*"]="Acer Chromebook 511|ADN|||"
	["CRAASNETO*"]="Acer Chromebook 314|ADN|||"
	["CRAASNETO-KYVC*"]="Acer Chromebook Plus 514|ADN|||"
	["CRAASWELL*"]="Acer Chromebook Spin 314|ADN|||"
	["DOMIKA*"]="HP Fortis G1i 11 Chromebook|ADN|||"
	["DOMILLY*"]="HP Fortis Flip G1i 11 Chromebook|ADN|||"
	["DOMISO*"]="HP Fortis G1i 14 Chromebook|ADN|||"
	["GALLIDA360*"]="Acer Chromebook Spin 311|ADN|||"
	["GANA*"]="CTL Chromebook PX111E|ADN|||"
	["GLASSWAY-IEIH*"]="Poin2 Chromebook Plus 14|ADN|||"
	["GLASSWAY-RKFM*"]="CTL Chromebook Plus PX141GX|ADN|||"
	["GLASSWAY-XVLV*"]="CTL Chromebook Enterprise PX141E|ADN|||"
	["GOTHRAX-FENM*"]="Gothrax|ADN|||"
	["GOTHRAX-LFWA*"]="Positivo Chromebook N2422|ADN|||"
	["GOTHRAX-LQNQ*"]="Centerm Chromebook M612B|ADN|||"
	["GOTHRAX-OEER*"]="aiwa Chromebook S11|ADN|||"
	["GOTHRAX-SKZO*"]="Multi Chromebook M11HC-PC925|ADN|||"
	["GOTHRAX-UZGM*"]="Acer Chromebook Spin 311(ROA732LTN)|ADN|||"
	["GOTHRAXCS-AIBU*"]="Centerm Chromebook M612A|ADN|||"
	["GOTHRAXCS-GTCE*"]="GothraxCS|ADN|||"
	["GOTHRAXCS-PTVI*"]="Positivo Chromebook N2420|ADN|||"
	["GOTHRAXCS-TXQV*"]="Multi Chromebook M11C-PC926|ADN|||"
	["GUREN-QPEQ*"]="CTL Chromebook PX121E|ADN|||"
	["GUREN-XQKZ*"]="Pegatron CA31T|ADN|||"
	["HIDEO-DZJX**"]="Hideo CBX Development Project|ADN|||"
	["HIDEO-JDWQ*"]="Centerm Chromebook Plus M621|ADN|||"
	["HIDEO-NKMK**"]="Hideo non-CBX Development Project|ADN|||"
	["HIDEO-ZBXY*"]="Centerm Chromebook M621|ADN|||"
	["JOXER*"]="HP Chromebook x360 14b|ADN|||"
	["PUJJO"]="Lenovo 500e Yoga/Flex 3i Chromebook|ADN|||"
	["PUJJO-DCCV*"]="Lenovo Flex 3i Chromebook 12\"|ADN|||"
	["PUJJO-KTLR*"]="Lenovo 500e Yoga Chromebook Gen 4|ADN|||"
	["PUJJO1E*"]="Lenovo 100e Chromebook Gen 4 (Intel)|ADN|||"
	["PUJJOFLEX*"]="Lenovo IdeaPad Flex 3i Chromebook|ADN|||"
	["PUJJOGA*"]="Lenovo 500e Chromebook Gen 4s|ADN|||"
	["PUJJOGATWIN*"]="Lenovo 500e Chromebook Gen 4s|ADN|||"
	["PUJJOTEEN"]="Lenovo 14e Chromebook Gen 3|ADN|||"
	["PUJJOTEEN | PUJJOTEEN*-CZPM* | PUJJOTEEN-JQII*"]="Lenovo 14e Chromebook Gen 3|ADN|||"
	["PUJJOTEEN*-KCBW* | PUJJOTEEN*-JQLW* | PUJJOTEEN15W"]="Lenovo Ideapad Slim 3i Chromebook|ADN|pujjoteen15w||"
	["QUANDISO*"]="CTL Chromebook NL73|ADN|||"
	["QUANDISO360*"]="CTL Chromebook NL73T|ADN|||"
	["RIVEN*"]="Acer Chromebook Spin 511|ADN|||"
	["RORIC*"]="Acer Chromebook Plus 514(CB514-6H|ADN|||"
	["RUDRIKS*"]="Acer Chromebook Spin 512|ADN|||"
	["RUKE-MCIP*"]="Acer Chromebook 315 (CB315-6H)|ADN|||"
	["RULL-MLST*"]="Acer Chromebook 514 (C937)|ADN|||"
	["RYNAX-DUSQ*"]="Acer Chromebook 511 (C737)|ADN|||"
	["SUNDANCE*"]="NEC Chromebook Y4|ADN|||"
	["TELIKS*"]="ASUS Chromebook CR11 (CR1104CTA)|ADN|||"
	["TELIKS360*"]="ASUS Chromebook CR11 Flip (CR1104FTA)|ADN|||"
	["TELITH*"]="ASUS Chromebook CX15 (CX1505CTA)|ADN|||"
	["TELTIC*"]="ASUS Chromebook CX14 (CX1405CTA)|ADN|||"
	["ULDREN*"]="Dell Chromebook 3120|ADN|||"
	["ULDREN360*"]="Dell Chromebook 3120 2-in-1|ADN|||"
	["XIVU*"]="Asus Chromebook CR11 [CR1102C]|ADN|||"
	["XIVU360*"]="Asus Chroembook CR11 [CR1102F]|ADN|||"
	["YAHIKO*"]="HP Chromebook Plus 14a|ADN|||"
	["YAVIJO*"]="HP Fortis 14 G11 Chromebook|ADN|||"
	["YAVIKS*"]="HP Chromebook 15.6|ADN|||"
	["YAVILLA*"]="HP Fortis 11 G10 Chromebook|ADN|||"
	["YAVILLY*"]="HP Fortis x360 11 G5 Chromebook|ADN|||"

	# MTL devices - Intel Meteorlake
	["KARIS*"]="Acer Chromebook Plus Spin 714|MTL|||"
	["REX*"]="ASUS ExpertBook CX54 Chromebook Plus (CX5403)|MTL|||"
	["SCREEBO*"]="ASUS ExpertBook CX54 Chromebook Plus (CX5403)|MTL|||"

	## AMD Devices

	# STR devices - AMD StoneyRidge
	["ALEENA*"]="Acer Chromebook 315|STR|||"
	["BARLA*"]="HP Chromebook 11A G6 EE|STR|||"
	["CAREENA*"]="HP Chromebook 14|STR|||"
	["GRUNT*"]="Acer Chromebook 315|STR|||"
	["KASUMI*"]="Acer Chromebook 311|STR|kasumi||"
	["LIARA*"]="Lenovo 14e Chromebook|STR|||"
	["TREEYA*"]="Lenovo 100e Chromebook 2nd Gen AMD|STR|||"
	["TREEYA360*"]="Lenovo 300e Chromebook 2nd Gen AMD|STR|treeya||"

	# PCO devices - AMD Picasso
	["BERKNIP*"]="HP Pro c645 Chromebook Enterprise|PCO|||"
	["DIRINBOZ*"]="HP Chromebook 14a|PCO|||"
	["EZKINIL*"]="Acer Chromebook Spin 514|PCO|||"
	["GUMBOZ*"]="HP Chromebook x360 14a|PCO|||"
	["JELBOZ360*"]="ASUS Chromebook Flip CM1 (CM1400)|PCO|||"
	["MORPHIUS*"]="Lenovo ThinkPad C13 Yoga Chromebook|PCO|||"
	["VILBOZ*"]="Lenovo 100e Chromebook Gen 3|PCO|||"
	["VILBOZ14*"]="Lenovo 14e Chromebook Gen 2|PCO|vilboz||"
	["VILBOZ360*"]="Lenovo 300e Chromebook Gen 3|PCO|vilboz||"
	["WOOMAX*"]="ASUS Chromebook Flip CM5|PCO|||"

	# CZN devices - AMD Cezanne
	["DEWATT*"]="Acer Chromebook Spin 514|CZN|||"
	["GUYBRUSH*"]="Guybrush Baseboard Chromebook|CZN|||"
	["NIPPERKIN*"]="HP Elite c645 G2 Chroembook|CZN|||"

	# MDN devices - AMD Mendocino
	["CRYSTALDRIFT*"]="TBD Skyrim Chromebook|MDN|||"
	["FROSTFLOW*"]="ASUS Chromebook CM34 Flip|MDN|||"
	["MARKARTH*"]="Acer Chromebook Plus 514|MDN|||"
	["SKYRIM*"]="Skyrim Baseboard Chromebook|MDN|||"
	["WHITERUN*"]="Dell Latitude 3445 Chromebook|MDN|||"


	## Non-ChromeOS devices
	["LIBREM13V1"]="Purism Librem 13 v1|BDW|librem13v1||"
	["LIBREM15V2"]="Purism Librem 15 v2|BDW|librem15v2||"
	["LIBREM13V2"]="Purism Librem 13 v2|SKL|||"
	["LIBREM13V3"]="Purism Librem 13 v3|SKL|||"
	["LIBREM15V3"]="Purism Librem 15 v3|SKL|||"
	["LIBREM_13_V2"]="Purism Librem 13 v2|SKL|librem13v2||"
	["LIBREM_13_V3"]="Purism Librem 13 v3|SKL|librem13v2||"
	["LIBREM_15_V3"]="Purism Librem 15 v3|SKL|librem15v3||"
	["LIBREM13V4"]="Purism Librem 13 v4|KBL|||"
	["LIBREM15V4"]="Purism Librem 15 v4|KBL|||"
	["LIBREM_13_V4"]="Purism Librem 13 v4|KBL|librem13v4||"
	["LIBREM_15_V4"]="Purism Librem 15 v4|KBL|librem15v4||"
	["LIBREM_MINI"]="Purism Librem Mini|WHL|librem_mini||"
	["LIBREM_14"]="Purism Librem 14|CML|librem_14||"
	["LIBREM_MINI_V2"]="Purism Librem Mini v2|CML|librem_mini_v2||"
)
