#!/bin/bash
#
#  Device Database
# Format: [HWID]="deviceDescription|CPU|device override|flags|"
# Flags: isCbox, hasLAN, kbl_rwl18, adl_fixed_rwl, noUEFI
#

# Declare the device database
declare -gA DEVICE_DB

# Populate the database
DEVICE_DB=(
	# SNB devices (EOL) - Intel SandyBridge
	["BUTTERFLY*"]="HP Pavilion Chromebook 14|SNB|||"
	["LUMPY*"]="Samsung Chromebook Series 5 550|SNB|||"
	["PARROT*"]="Acer C7/C710 Chromebook|SNB|||"
	["STUMPY*"]="Samsung Chromebox Series 3|SNB||isCbox,hasLAN|"

	# IVB devices (EOL) - Intel IvyBridge
	["LINK*"]="Google Chromebook Pixel (2013)|IVB|||"
	["STOUT*"]="Lenovo Thinkpad X131e Chromebook|IVB|||"

	# HSW devices (EOL) - Intel Haswell
	["FALCO*"]="HP Chromebook 14|HSW|||"
	["LEON*"]="Toshiba Chromebook 13 (CB30/CB35)|HSW|||"
	["MCCLOUD*"]="Acer Chromebox CXI|HSW||isCbox,hasLAN|"
	["MONROE*"]="LG Chromebase (22CB25S,22CV241)|HSW||,hasLAN|"
	["PANTHER*"]="ASUS Chromebox (CN60)|HSW||isCbox,hasLAN|"
	["PEPPY*"]="Acer Chromebook 11 (C720/C720P)|HSW|||"
	["TRICKY*"]="Dell Chromebox 3010|HSW||isCbox,hasLAN|"
	["WOLF*"]="Dell Chromebook 11|HSW|||"
	["ZAKO*"]="HP Chromebox G1|HSW||isCbox,hasLAN|"

	# BDW devices (EOL) - Intel Broadwell
	["AURON_PAINE*"]="Acer Chromebook 11 (C740)|BDW|||"
	["AURON_YUNA*"]="Acer Chromebook 15 (CB5-571, C910)|BDW|||"
	["BUDDY*"]="Acer Chromebase 24|BDW||hasLAN|"
	["GANDOF*"]="Toshiba Chromebook 2 (2015) CB30/CB35|BDW|||"
	["GUADO*"]="ASUS Chromebox 2 (CN62)|BDW||isCbox,hasLAN|"
	["LULU*"]="Dell Chromebook 13 (7310)|BDW|||"
	["PAINE*"]="Acer Chromebook 11 (C740)|BDW|auron_paine||"
	["RIKKU*"]="Acer Chromebox CXI2/CXV2|BDW||isCbox,hasLAN|"
	["SAMUS*"]="Google Chromebook Pixel (2015)|BDW|||"
	["TIDUS*"]="Lenovo ThinkCentre Chromebox|BDW||isCbox,hasLAN|"
	["YUNA*"]="Acer Chromebook 15 (CB5-571, C910)|BDW|auron_yuna||"

	# BYT devices (EOL) - Intel BayTrail
	["BANJO*"]="Acer Chromebook 15 (CB3-531)|BYT|||"
	["CANDY*"]="Dell Chromebook 11 (3120)|BYT|||"
	["CLAPPER*"]="Lenovo N20/N20P Chromebook|BYT|||"
	["ENGUARDE ???-???-??A*"]="CTL N6 Education Chromebook|BYT|||"
	["ENGUARDE ???-???-??B*"]="M&A Chromebook|BYT|||"
	["ENGUARDE ???-???-??C*"]="Senkatel C1101 Chromebook|BYT|||"
	["ENGUARDE ???-???-??D*"]="Edxis Education Chromebook|BYT|||"
	["ENGUARDE ???-???-??E*"]="Lenovo N21 Chromebook|BYT|||"
	["ENGUARDE ???-???-??F*"]="RGS Education Chromebook|BYT|||"
	["ENGUARDE ???-???-??G*"]="Crambo Chromebook|BYT|||"
	["ENGUARDE ???-???-??H*"]="True IDC Chromebook|BYT|||"
	["ENGUARDE ???-???-??I*"]="Videonet Chromebook|BYT|||"
	["ENGUARDE ???-???-??J*"]="eduGear Chromebook R|BYT|||"
	["ENGUARDE ???-???-??K*"]="ASI Chromebook|BYT|||"
	["ENGUARDE*"]="Enguarde BYT Chromebook|BYT|||"
	["EXPRESSO ???-???-??A*"]="HEXA Chromebook Pi|BYT|||"
	["EXPRESSO ???-???-??B*"]="Bobicus Chromebook 11|BYT|||"
	["EXPRESSO ???-???-??C*"]="Edxis Chromebook|BYT|||"
	["EXPRESSO*"]="Expresso BYT Chromebook|BYT|||"
	["GLIMMER*"]="Lenovo ThinkPad 11e/Yoga Chromebook|BYT|||"
	["GNAWTY*"]="Acer Chromebook 11 (CB3-111/131, C730/C730E/C735)|BYT|||"
	["HELI*"]="Haier Chromebook 11 G2|BYT|||"
	["KIP*"]="HP Chromebook 11 G3/G4, 14 G4|BYT|||"
	["NINJA*"]="AOpen Chromebox Commercial|BYT||isCbox,hasLAN|"
	["ORCO*"]="Lenovo IdeaPad 100S Chromebook|BYT|||"
	["QUAWKS*"]="ASUS Chromebook C300|BYT|||"
	["SQUAWKS*"]="ASUS Chromebook C200|BYT|||"
	["SUMO*"]="AOpen Chromebase Commercial|BYT||isCbox,hasLAN|"
	["SWANKY*"]="Toshiba Chromebook 2 (2014) CB30/CB35|BYT|||"
	["TERRA*"]="ASUS Chromebook C202SA/C300SA/C301SA|BYT|||"
	["WINKY*"]="Samsung Chromebook 2 (XE500C12)|BYT|||"

	# BSW devices (EOL) - Intel Braswell
	["BANON*"]="Acer Chromebook 15 (CB3-532)|BSW|||"
	["CELES*"]="Samsung Chromebook 3|BSW|||"
	["CYAN*"]="Acer Chromebook R11 (CB5-132T, C738T)|BSW|||"
	["EDGAR*"]="Acer Chromebook 14 (CB3-431)|BSW|||"
	["KEFKA*"]="Dell Chromebook 11 (3180,3189)|BSW|||"
	["REKS*"]="Lenovo N22/N23/N42 Chromebook|BSW|||"
	["RELM ???-H*"]="Acer Chromebook 11 N7 (C731)|BSW|||"
	["RELM ???-B*"]="CTL NL61 Chromebook|BSW|||"
	["RELM ???-C*"]="Edxis Education Chromebook|BSW|||"
	["RELM ???-F*"]="Mecer V2 Chromebook|BSW|||"
	["RELM ???-G*"]="HP Chromebook 11 G5 EE|BSW|||"
	["RELM ???-Z*"]="Quanta OEM Chromebook|BSW|||"
	["RELM*"]="Relm BSW Chromebook|BSW|||"
	["SETZER*"]="HP Chromebook 11 G5|BSW|||"
	["TERRA*"]="ASUS Chromebook C202SA, C300SA/C301SA|BSW|||"
	["TERRA ???-???-???-A*"]="ASUS Chromebook C202SA|BSW|||"
	["TERRA ???-???-???-B*"]="ASUS Chromebook C300SA/C301SA|BSW|||"
	["ULTIMA*"]="Lenovo ThinkPad 11e/Yoga Chromebook (G3)|BSW|||"
	["WIZPIG*"]="Wizpig BSW Chromebook|BSW|||"
	["WIZPIG ???-???-??A*"]="CTL J5 Chromebook|BSW|||"
	["WIZPIG ???-???-??B*"]="Edugear CMT Chromebook|BSW|||"
	["WIZPIG ???-???-??C*"]="Haier Convertible Chromebook 11 C|BSW|||"
	["WIZPIG ???-???-??D*"]="Viglen Chromebook 360|BSW|||"
	["WIZPIG ???-???-??G*"]="Prowise Chromebook ProLine|BSW|||"
	["WIZPIG ???-???-??H*"]="PCMerge Chromebook PCM-116T-432B|BSW|||"
	["WIZPIG ???-???-??I*"]="Multilaser Chromebook M11C|BSW|||"

	# SKL devices (EOL) - Intel Skylake
	["ASUKA*"]="Dell Chromebook 13 (3380)|SKL|||"
	["CAROLINE*"]="Samsung Chromebook Pro|SKL|||"
	["CAVE*"]="ASUS Chromebook Flip C302|SKL|||"
	["CHELL*"]="HP Chromebook 13 G1|SKL|||"
	["LARS*"]="Acer Chromebook 14 for Work, Chromebook 11 (C771, C771T)|SKL|||"
	["SENTRY*"]="Lenovo Thinkpad 13 Chromebook|SKL|||"

	# APL devices - Intel ApolloLake
	["ASTRONAUT*"]="Acer Chromebook 11 (C732)|APL|coral||"
	["BABYMEGA*"]="Asus Chromebook C223NA|APL|coral||"
	["BABYTIGER*"]="Asus Chromebook C523NA|APL|coral||"
	["BLACKTIP*"]="CTL Chromebook NL7|APL|coral||"
	["BLUE*"]="Acer Chromebook 15 [CB315-1H/1HT]|APL|coral||"
	["BRUCE*"]="Acer Chromebook Spin 15 [CP315]|APL|coral||"
	["CORAL*"]="Incorrectly identified APL Chromebook|APL|||"
	["ELECTRO*"]="Acer Chromebook Spin 11 (R751T)|APL|reef||"
	["EPAULETTE*"]="Acer Chromebook 514 (CB514-1H, CB514-1HT)|APL|coral||"
	["LAVA*"]="Acer Chromebook Spin 11 CP311|APL|coral||"
	["NASHER*"]="Dell Chromebook 11 5190|APL|coral||"
	["NASHER360*"]="Dell Chromebook 11 2-in-1 5190|APL|coral||"
	["PYRO*"]="Lenovo Thinkpad 11e/Yoga Chromebook (G4)|APL|||"
	["RABBID*"]="ASUS Chromebook C423/CX1400|APL|coral||"
	["REEF*"]="ASUS Chromebook C213NA|APL|||"
	["REEF ???-B*"]="Acer Chromebook Spin 11 (R751T)|APL|||"
	["ROBO*"]="Lenovo 100e Chromebook|APL|coral||"
	["ROBO360*"]="Lenovo 500e Chromebook|APL|coral||"
	["SAND*"]="Acer Chromebook 15 (CB515-1HT)|APL|||"
	["SANTA*"]="Acer Chromebook 11 (CB311-8H)|APL|coral||"
	["SNAPPY*"]="HP Chromebook 11-ae0/ae1, 11 G6 EE, 14-ca0/ca1|APL|||"
	["WHITETIP*"]="CTL Chromebook J41/J41T|APL|coral||"

	# KBL devices - Intel KabyLake
	["AKALI*"]="Acer Chromebook 13 / Spin 13|KBL|nami||"
	["ATLAS*"]="Google Pixelbook Go|KBL||kbl_rwl18|"
	["BARD*"]="Acer Chromebook 715 (CB715)|KBL|nami||"
	["EKKO*"]="Acer Chromebook 714 (CB714)|KBL|nami||"
	["ENDEAVOUR*"]="Google Meet Series One (Lenovo)|KBL||isCbox,kbl_rwl18|"
	["EVE*"]="Google Pixelbook|KBL|||"
	["EXCELSIOR*"]="Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["EXCELSIOR-OOLH*"]="CTL Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["EXCELSIOR-URAR*"]="Asus Google Meet kit (KBL)|KBL|fizz|isCbox,hasLAN|"
	["FIZZ*"]="Fizz KBL Chromebox|KBL||isCbox,hasLAN|"
	["JAX*"]="AOpen Chromebox Commercial 2|KBL|fizz|isCbox,hasLAN|"
	["KARMA*"]="Acer Chromebase 24I2|KBL||kbl_rwl18|"
	["KENCH*"]="HP Chromebox G2|KBL|fizz|isCbox,hasLAN|"
	["LEONA*"]="Asus Chromebook C425TA|KBL|rammus|kbl_rwl18|"
	["NAMI*"]="NAMI Chromebook (multi)|KBL|nami||"
	["NAUTILUS*"]="Samsung Chromebook Plus V2|KBL|||"
	["NOCTURNE*"]="Google Pixel Slate|KBL||kbl_rwl18|"
	["PANTHEON*"]="Lenovo Yoga Chromebook C630|KBL|nami||"
	["RAMMUS*"]="Asus Chromebook C425/C433/C434|KBL|||"
	["SHYVANA*"]="Asus Chromebook Flip C433/C434|KBL|rammus|kbl_rwl18|"
	["SION*"]="Acer Chromebox CXI3|KBL|fizz|isCbox,hasLAN|"
	["SONA*"]="HP Chromebook x360 14|KBL|nami||"
	["SORAKA*"]="HP Chromebook x2|KBL|||"
	["SYNDRA*"]="HP Chromebook 15 G1|KBL|nami||"
	["TEEMO*"]="Asus Chromebox 3 / CN65|KBL|fizz|isCbox,hasLAN|"
	["VAYNE*"]="Dell Inspiron Chromebook 14 (7486)|KBL|nami||"
	["WUKONG ??C*"]="ViewSonic NMP660 Chromebox|KBL|fizz|isCbox,hasLAN|"
	["WUKONG ??D*"]="CTL Chromebox CBx1|KBL|fizz|isCbox,hasLAN|"
	["WUKONG ??H*"]="Promethean Chromebox|KBL|fizz|isCbox,hasLAN|"
	["WUKONG ??I*"]="SMART Chromebox G3|KBL|fizz|isCbox,hasLAN|"
	["WUKONG*"]="Fizz-based 7th/8th-gen Chromebox|KBL|fizz|isCbox,hasLAN|"

	# GLK devices - Intel GeminiLake
	["AMPTON*"]="Asus Chromebook Flip C214/C234|GLK|||"
	["APEL*"]="Asus Chromebook Flip C204|GLK|ampton||"
	["APELE*"]="Asus Chromebook CX1101CMA|GLK|apel||"
	["BLOOG*"]="HP Chromebook x360 12b|GLK|||"
	["BLOOGLET*"]="HP Chromebook 14a|GLK|bloog||"
	["BLOOGUARD*"]="HP Chromebook x360 14a/14b|GLK|bloog||"
	["BLORB*"]="Acer Chromebook 315|GLK|bobba||"
	["BLUEBIRD*"]="Samsung Chromebook 4|GLK|casta||"
	["BOBBA*"]="Acer Chromebook 311|GLK|||"
	["BOBBA360*"]="Acer Chromebook Spin 311/511|GLK|bobba||"
	["CASTA*"]="Samsung Chromebook 4+|GLK|||"
	["DOOD*"]="NEC Chromebook Y2|GLK|||"
	["DORP*"]="HP Chromebook 14 G6|GLK|meep||"
	["DROID*"]="Acer Chromebook 314|GLK|bobba||"
	["FLEEX*"]="Dell Chromebook 3100|GLK|||"
	["FOOB*"]="CTL Chromebook VX11/VT11T|GLK|||"
	["GARFOUR*"]="CTL Chromebook NL81/NL81T|GLK|garg||"
	["GARG*"]="CTL Chromebook NL71/CT/LTE|GLK|||"
	["GARG360*"]="CTL Chromebook NL71T/TW/TWB|GLK|garg||"
	["GRABBITER*"]="Dell Chromebook 3100 2-in-1|GLK|fleex||"
	["LASER*"]="Lenovo Chromebook C340|GLK|phaser||"
	["LASER14*"]="Lenovo Chromebook S340 / IdeaPad 3|GLK|phaser||"
	["LICK*"]="Lenovo Ideapad 3 Chromebook|GLK|||"
	["MEEP*"]="HP Chromebook x360 11 G2 EE|GLK|||"
	["MIMROCK*"]="HP Chromebook 11 G7 EE|GLK|meep||"
	["NOSPIKE*"]="ASUS Chromebook C424|GLK|ampton||"
	["ORBATRIX*"]="Dell Chromebook 3400|GLK|fleex||"
	["PHASER*"]="Lenovo 100e Chromebook 2nd Gen|GLK|||"
	["PHASER360*"]="Lenovo 300e/500e Chromebook 2nd Gen|GLK|phaser||"
	["SPARKY*"]="Acer Chromebook 512 (C851/C851T)|GLK|bobba||"
	["SPARKY360*"]="Acer Chromebook Spin 512 (R851TN)|GLK|bobba||"
	["VORTICON*"]="HP Chromebook 11 G8 EE|GLK|meep||"
	["VORTININJA*"]="HP Chromebook x360 11 G3 EE|GLK|meep||"

	# WHL devices - Intel WhiskeyLake
	["ARCADA*"]="Dell Latitude 5300|WHL|sarien|noUEFI|"
	["SARIEN*"]="Dell Latitude 5400|WHL||noUEFI|"

	# CML devices - Intel CometLake
	# Hatch baseboard
	["AKEMI*"]="Lenovo IdeaPad Flex 5i Chromebook|CML|||"
	["DRAGONAIR*"]="HP Chromebook x360 14c|CML|dratini||"
	["DRATINI*"]="HP Pro c640 Chromebook|CML|||"
	["HELIOS*"]="ASUS Chromebook Flip C436FA|CML|||"
	["JINLON*"]="HP Elite c1030 Chromebook / HP Chromebook x360 13c|CML|||"
	["KINDRED*"]="Acer Chromebook 712 [C871]|CML|||"
	["KLED*"]="Acer Chromebook Spin 713 (CP713-2W)|CML|kindred||"
	["KOHAKU*"]="Samsung Galaxy Chromebook|CML|||"
	["NIGHTFURY*"]="Samsung Galaxy Chromebook 2|CML|||"
	# Puff baseboard
	["AMBASSADOR*"]="CTL Meet Compute System GQE15C|CML||isCbox,hasLAN|"
	["DOOLY*"]="HP Chromebase 21.5|CML||isCbox,hasLAN|"
	["DUFFY*"]="ASUS Chromebox 4|CML||isCbox,hasLAN|"
	["FAFFY*"]="ASUS Fanless Chromebox|CML||isCbox,hasLAN|"
	["GENESIS*"]="Google Meet Series One (Intel 10th Gen)|CML||isCbox,hasLAN|"
	["KAISA*"]="Acer Chromebox CXI4|CML||isCbox,hasLAN|"
	["MOONBUGGY*"]="Avocor Series One Board 65|CML||isCbox,hasLAN|"
	["NOIBAT*"]="HP Chromebox G3|CML||isCbox,hasLAN|"
	["SCOUT*"]="Avocor Series One Desk 27|CML||isCbox,hasLAN|"
	["WYVERN-JLOF*"]="CTL Chromebox CBx2|CML||isCbox,hasLAN|"
	["WYVERN-HOIZ*"]="Wyvern MobLab|CML||isCbox,hasLAN|"
	["WYVERN-JOTV*"]="Promethean Chromebox 2|CML||isCbox,hasLAN|"
	["WYVERN-JRVR*"]="ViewSonic NMP760 Chromebox|CML||isCbox,hasLAN|"
	["WYVERN*"]="Wyvern CML Chromebox|CML||isCbox,hasLAN|"
	# Drallion baseboard
	["DRALLION*"]="Dell Latitude 7410 Chromebook Enterprise|CML|drallion||"


	# JSL devices - Intel JasperLake
	["AWADORON*"]="ASUS Chromebook CX1505CKA|JSL|awasuki||"
	["AWASUKI*"]="ASUS Chromebook CX1405CKA/CB1405CKA|JSL|||"
	["BEADRIX-GPPJ*"]="DINATECH Gen1 Chromebook  SG20JL1C|JSL|||"
	["BEADRIX-RIJZ*"]="Multilaser Chromebook M11C-PC919|JSL|||"
	["BEADRIX-ULGS*"]="Evolve III Chromebook 11 E1|JSL|||"
	["BEADRIX-XEER*"]="Positivo Chromebook N2320|JSL|||"
	["BEADRIX-XYBG*"]="Allied Chromebook 11 N5100EO-864180|JSL|||"
	["BEADRIX*"]="Beadrix JSL Chromebook|JSL|||"
	["BEETLEY*"]="Lenovo Flex 3i Chromebook 15 IdeaPad Flex 3i Chromebook|JSL|blipper||"
	["BLIPPER*"]="Lenovo 3i-15 Chromebook|JSL|||"
	["BOOKEM*"]="Lenovo Chromebook 11 / 100e Gen 3|JSL|boten||"
	["BOTENFLEX*"]="Lenovo Flex 3i-11 Chromebook|JSL|boten||"
	["BOTEN*"]="Lenovo 500e Chromebook Gen 3|JSL|||"
	["BOXY*"]="Lenovo Chromebox Micro|JSL||isCbox,hasLAN|"
	["BUGZZY*"]="Samsung Galaxy Chromebook 2 360|JSL|||"
	["CRET360*"]="Dell Chromebook 3110 2-in-1|JSL|cret||"
	["CRET*"]="Dell Chromebook 3110|JSL|||"
	["DEXI*"]="AOPEN Chromebox Mini 2|JSL||isCbox,hasLAN|"
	["DITA*"]="Acer Chromebox Mini CXM1|JSL||isCbox,hasLAN|"
	["DITA-AZYL*"]="AOPEN Chromebox P1|JSL||isCbox,hasLAN|"
	["DRAWCIA*"]="HP Chromebook x360 11 G4 EE|JSL|||"
	["DRAWLAT*"]="HP Chromebook 11 G9 EE|JSL|drawcia||"
	["DRAWMAN*"]="HP Chromebook 14 G7|JSL|drawcia||"
	["DRAWPER*"]="HP Fortis 14 G10 Chromebook|JSL|drawcia||"
	["GALITH360*"]="ASUS Chromebook CX1500FKA|JSL|galtic||"
	["GALITH*"]="ASUS Chromebook CX1500CKA|JSL|galtic||"
	["GALLOP*"]="ASUS Chromebook CX1700CKA|JSL|galtic||"
	["GALNAT360*"]="ASUS Chromebook Flip CX1 CX1102|JSL|galtic||"
	["GALNAT*"]="ASUS Chromebook CX1 CX1102|JSL|galtic||"
	["GALTIC360*"]="ASUS Chromebook CX1400FKA|JSL|galtic||"
	["GALTIC*"]="ASUS Chromebook CX1400CKA|JSL|||"
	["KRACKO360-BLXA*"]="CTL Chromebook NL72T|JSL|kracko||"
	["KRACKO360-CPOG*"]="Positivo Chromebook N2312|JSL|kracko||"
	["KRACKO360-LGAB*"]="LG Chromebook 11TC50Q|JSL|kracko||"
	["KRACKO360-SYDL*"]="Poin2 Chromebook 11E|JSL|kracko||"
	["KRACKO-DJBB*"]="Poin2 Chromebook 11B|JSL|||"
	["KRACKO-DQEL*"]="Centerm Chromebook M610|JSL|||"
	["KRACKO-HBBG*"]="ADVAN Chromebook 116J|JSL|||"
	["KRACKO-RVAR*"]="Zyrex Chromebook M432-64|JSL|||"
	["KRACKO-WPBT*"]="CTL Chromebook NL72|JSL|||"
	["KRACKO-WYQT*"]="Edxis Chromebook 11 (S30-C)|JSL|||"
	["KRACKO-XJKD*"]="Multilaser Chromebook M11HC-PC916|JSL|||"
	["KRACKO-YKWP*"]="Positivo Chromebook N2310|JSL|||"
	["KRACKO360*"]="Kracko 360 JSL Chromebook|JSL|kracko||"
	["KRACKO*"]="Kracko JSL Chromebook|JSL|||"
	["LANDIA*"]="HP Chromebook x360 14a-ca1|JSL|lantis||"
	["LANDRID*"]="HP Chromebook 15a|JSL|lantis||"
	["LANTIS*"]="HP Chromebook 14a|JSL|||"
	["MADOO*"]="HP Chromebook x360 14b|JSL|||"
	["MAGISTER*"]="Acer Chromebook Spin 314|JSL|magolor||"
	["MAGLET*"]="Acer Chromebook 512 (C852)|JSL|magolor||"
	["MAGLIA*"]="Acer Chromebook Spin 512|JSL|magolor||"
	["MAGLITH*"]="Acer Chromebook 511|JSL|magolor||"
	["MAGMA*"]="Acer Chromebook 315|JSL|magolor||"
	["MAGNETO-BWYB*"]="Acer Chromebook 314|JSL|magolor||"
	["MAGNETO-SGGB*"]="Packard Bell Chromebook 314|JSL|magolor||"
	["MAGNETO*"]="Magneto JSL Chromebook|JSL|magolor||"
	["MAGOLOR*"]="Acer Chromebook Spin 511|JSL|||"
	["MAGPIE*"]="Acer Chromebook 317|JSL|magolor||"
	["METAKNIGHT*"]="NEC Chromebook Y3|JSL|||"
	["PALUTENA-JOWH*"]="CA14J2|JSL|pirika||"
	["PALUTENA-TQFG*"]="Gateway Chromebook 314|JSL|pirika||"
	["PALUTENA-YVYF*"]="Acer Chromebook 314|JSL|pirika||"
	["PALUTENA*"]="Palutena JSL Chromebook|JSL|pirika||"
	["PASARA-RTKU*"]="Edxis E-Lite Chromebook 15|JSL|pirika||"
	["PASARA-TZNR*"]="Gateway Chromebook 15|JSL|pirika||"
	["PASARA*"]="Pasara JSL Chromebook|JSL|pirika||"
	["PEEZER-ABCD*"]="CA11J2 45Wh|JSL|pirika||"
	["PEEZER-EUBP*"]="Multilaser Chromebook M11C-PC924|JSL|pirika||"
	["PEEZER-FYEL*"]="CTL Chromebook PX11EG|JSL|pirika||"
	["PEEZER-LXVK*"]="Acer Chromebook 311(CO731)|JSL|pirika||"
	["PEEZER-PKZD*"]="Edxis E-Lite Chromebook 11|JSL|pirika||"
	["PEEZER-RRAJ*"]="Gateway Chromebook 311|JSL|pirika||"
	["PEEZER-UGDD*"]="CA11J2|JSL|pirika||"
	["PEEZER-ZQNH*"]="Zyrex Chromebook M432-2P|JSL|pirika||"
	["PEEZER*"]="Peezer JSL Chromebook|JSL|pirika||"
	["PIRETTE-AZUJ*"]="Allied Chromebook 11 N5100P|JSL|pirika||"
	["PIRETTE-LLJI*"]="Axioo Chromebook P11|JSL|pirika||"
	["PIRETTE-NGVJ*"]="SPC Chromebook Z1 Mini|JSL|pirika||"
	["PIRETTE-RVKU*"]="CTL Chromebook PX11E|JSL|pirika||"
	["PIRETTE-UBKE*"]="Zyrex Chromebook M432-2|JSL|pirika||"
	["PIRETTE*"]="Pirette JSL Chromebook|JSL|pirika||"
	["PIRIKA-BMAD*"]="CTL Chromebook Enterprise|JSL|||"
	["PIRIKA-CMMK*"]="Arai Nimbus S1 Chromebook Enterprise|JSL|||"
	["PIRIKA-NPXS*"]="Axioo Chromebook P14|JSL|||"
	["PIRIKA-OXAV*"]="Edxis E-Lite Chromebook 14|JSL|||"
	["PIRIKA-XAJY*"]="Gateway Chromebook 14|JSL|||"
	["PIRIKA*"]="Pirika JSL Chromebook|JSL|||"
	["SASUKE*"]="Samsung Galaxy Chromebook Go|JSL|||"
	["SASUKETTE*"]="Samsung Galaxy Chromebook Go 11|JSL|||"
	["STORO360*"]="ASUS Chromebook Flip CR1100FKA|JSL|storo||"
	["STORO*"]="ASUS Chromebook CR1100CKA|JSL|||"
	["TARANZA*"]="ASUS Fanless Chromebox CF40|JSL||isCbox,hasLAN|"

	# TGL devices - Intel TigerLake
	["CHRONICLER*"]="FMV Chromebook 14F|TGL|||"
	["COLLIS*"]="ASUS Chromebook Flip CX3|TGL|||"
	["COPANO*"]="ASUS Chromebook Flip CX5 (CX5400)|TGL|||"
	["DELBIN*"]="ASUS Chromebook Vibe CX5/CX55 (C536)|TGL|||"
	["DROBIT*"]="ASUS Chromebook CX9 (CX9400)|TGL|||"
	["ELDRID*"]="HP Chromebook x360 14c-cc0|TGL|||"
	["ELEMI*"]="HP Chromebook 14b-nb0|TGL|||"
	["LILLIPUP*"]="Lenovo IdeaPad Flex 5i Chromebook|TGL|lindar||"
	["LINDAR*"]="Lenovo Slim 5/5i-14 Chromebook|TGL|||"
	["VOEMA*"]="Acer Chromebook Spin 514 (CP514-2H)|TGL|||"
	["VOLET*"]="Acer Chromebook 515 (CB515-1W/CB515-1WT)|TGL|||"
	["VOLTA*"]="Acer Chromebook 514 (CB514-1W/CB514-1WT)|TGL|voxel||"
	["VOXEL*"]="Acer Chromebook Spin 713 (CP713-3W)|TGL|||"

	# ADL devices - Intel AlderLake/RaptorLake-U/P
	# Brya baseboard
	["ANAHERA*"]="HP Elite c640 14 inch G3 Chromebook|ADL|||"
	["BANSHEE*"]="Framework Laptop Chromebook Edition|ADL||adl_fixed_rwl|"
	["CROTA*"]="Dell Latitude 5430 Chromebook|ADL|||"
	["CROTA360*"]="Dell Latitude 5430 2-in-1 Chromebook|ADL|crota||"
	["DOCHI*"]="Acer Chromebook Plus Spin 514 (CP514-4HN, CPE594-1N, CPE594-1N)|ADL|||"
	["FELWINTER*"]="ASUS Chromebook Flip CX5(CX5601)|ADL|||"
	["GIMBLE*"]="HP Chromebook x360 14c-cd0|ADL||adl_fixed_rwl|"
	["KANO*"]="Acer Chromebook Spin 714 (CP714-1WN/2WN)|ADL|||"
	["MARASOV*"]="ASUS Chromebook Plus CX34 CX3402|ADL||adl_fixed_rwl|"
	["MITHRAX*"]="ASUS Chromebook CX34 Flip (CX3401)|ADL|||"
	["OMNIGUL*"]="Acer Chromebook Plus 515 (CB515-2H/2HT)|ADL||adl_fixed_rwl|"
	["OMNIKNIGHT*"]="Acer Chromebook Plus Enterprise 515 (CBE595-2/2T)|ADL|omnigul||"
	["OSIRIS*"]="Acer Chromebook 516 GE (CBG516-1H/2H)|ADL||adl_fixed_rwl|"
	["PRIMUS*"]="Lenovo ThinkPad C14 Gen 1 Chromebook|ADL|||"
	["REDRIX*"]="HP Elite Dragonfly Chromebook|ADL||adl_fixed_rwl|"
	["TAEKO*"]="Lenovo IdeaPad/Flex 5i Chromebook 14|ADL|||"
	["TANIKS*"]="Lenovo IdeaPad Gaming Chromebook 16|ADL|||"
	["TARLO*"]="Lenovo IdeaPad 5i Chromebook 16|ADL|taeko||"
	["VELL*"]="HP Dragonfly Pro Chromebook|ADL|||"
	["VOLMAR*"]="Acer Chromebook Vero 514|ADL|||"
	["XOL*"]="Galaxy Chromebook Plus|ADL||adl_fixed_rwl|"
	["ZAVALA*"]="Acer Chromebook Vero 712 (CV872/CV872T)|ADL|volmar||"
	# Brask baseboard
	["AURASH*"]="AOpen Chromebox Commercial 3|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA-FWVA*"]="Satsuki Chromebox OPS|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA-HJOB*"]="ViewSonic Bujia|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA-IFBL*"]="AOPEN Chromebox OPS|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA-TEDS*"]="Bujia Development Product|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA-XMII*"]="IMAGO Chromebox OPS|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["BUJIA*"]="Bujia ADL Chromebox|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["GLADIOS*"]="HP Chromebox Enterprise G4|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["KINOX*"]="Lenovo ThinkCentre M60q Chromebox|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["KULDAX*"]="ASUS Chromebox 5/5a (CN67)|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON-GURF*"]="CTL Chromebox CBx3|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON-IGDX*"]="Promethean Chromebox 3|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON-TVCI*"]="Lisbon Development Product|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON-WFCT*"]="Centerm Chromebox D661|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["LISBON*"]="Lisbon ADL Chromebox|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["MOLI*"]="Acer Chromebox CXI5|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	["MOXIE*"]="Acer Chromebox CXI6|ADL||isCbox,hasLAN,adl_fixed_rwl|"
	# Brask baseboard / constitution recovery image
	["CONSTITUTION*"]="Google Meet Series Two|ADL||adl_fixed_rwl|"
	["INTREPID*"]="CTL Meet Compute System GQE20C|ADL|constitution|isCbox,hasLAN,adl_fixed_rwl|"
	# Brox baseboard
	["JUBILANT*"]="Acer Chromebook Plus 514|ADL||noUEFI|"
	["JUBILEUM*"]="Acer Chromebook Plus 516|ADL|jubilant|noUEFI|"
	["LOTSO*"]="Lenovo Chromebook Plus 2-in-1|ADL||noUEFI|"

	# ADN devices - Intel AlderLake-N
	["ANRAGGAR360*"]="ASUS Chromebook CR12 flip CR1204F|ADN|anraggar||"
	["ANRAGGAR*"]="ASUS Chromebook CR12 CR1204C|ADN|||"
	["CRAASK*"]="Acer Chromebook Spin 512|ADN|||"
	["CRAASKANA*"]="Acer Chromebook 311|ADN|craask||"
	["CRAASKBOWL*"]="Acer Chromebook Spin 511|ADN|craask||"
	["CRAASKINO*"]="Acer Chromebook 315|ADN|craask||"
	["CRAASKOV*"]="Acer Chromebook Spin 312 (CP312-1H, CP312-1HN)|ADN|||"
	["CRAASKVIN*"]="Acer Chromebook 511|ADN|craask||"
	["CRAASNETO*"]="Acer Chromebook 314/514|ADN|craask||"
	["CRAASWELL*"]="Acer Chromebook Spin 314|ADN|craask||"
	["DIRKS*"]="Acer Chromebox Mini CXM2 (TWL)|ADN|||"
	["DOMIKA*"]="HP Fortis G1i 11 Chromebook|ADN|||"
	["DOMILLY*"]="HP Fortis Flip G1i 11 Chromebook|ADN|domika||"
	["DOMISO*"]="HP Fortis G1i 14 Chromebook|ADN|domika||"
	["GALLIDA360*"]="Acer Chromebook Spin 311|ADN|glassway||"
	["GANA*"]="CTL Chromebook PX111E|ADN|glassway||"
	["GLASSWAY-IEIH*"]="Poin2 Chromebook Plus 14|ADN|||"
	["GLASSWAY-RKFM*"]="CTL Chromebook Plus PX141GX|ADN|||"
	["GLASSWAY-XVLV*"]="CTL Chromebook Enterprise PX141E|ADN|||"
	["GLASSWAY*"]="Glassway ADL-N Chromebook|ADN|||"
	["GOTHRAXCS-AIBU*"]="Centerm Chromebook M612A|ADN|gothrax||"
	["GOTHRAXCS-GTCE*"]="GothraxCS|ADN|gothrax||"
	["GOTHRAXCS-PTVI*"]="Positivo Chromebook N2420|ADN|gothrax||"
	["GOTHRAXCS-TXQV*"]="Multi Chromebook M11C-PC926|ADN|gothrax||"
	["GOTHRAXCS*"]="GothraxCS ADL-N Chromebook|ADN|gothrax||"
	["GOTHRAX-FENM*"]="Gothrax|ADN|||"
	["GOTHRAX-LFWA*"]="Positivo Chromebook N2422|ADN|||"
	["GOTHRAX-LQNQ*"]="Centerm Chromebook M612B|ADN|||"
	["GOTHRAX-OEER*"]="Aiwa Chromebook S11|ADN|||"
	["GOTHRAX-SKZO*"]="Multi Chromebook M11HC-PC925|ADN|||"
	["GOTHRAX-UZGM*"]="Acer Chromebook Spin 311(ROA732LTN)|ADN|||"
	["GOTHRAX*"]="Gothrax ADL-N Chromebook|ADN|||"
	["GUREN360*"]="Poin2 Chromebook 12P / Pegatron CA32TC|ADN|guren||"
	["GUREN*"]="Pegatron CA31T / CTL Chromebook PX121E|ADN|||"
	["HIDEO*"]="Centerm Chromebook M621|ADN|gothrax||"
	["JOXER*"]="HP Chromebook x360 14b|ADN|||"
	["PUJJO-DCCV*"]="Lenovo Flex 3i Chromebook 12\"|ADN|||"
	["PUJJO-KTLR*"]="Lenovo 500e Yoga Chromebook Gen 4|ADN|||"
	["PUJJO1E*"]="Lenovo 100e Chromebook Gen 4 (Intel)|ADN|pujjo||"
	["PUJJOFLEX*"]="Lenovo IdeaPad Flex 3i Chromebook|ADN|pujjo||"
	["PUJJOGA*"]="Lenovo 500e Chromebook Gen 4s|ADN|||"
	["PUJJOGATWIN*"]="Lenovo 500e Chromebook Gen 4s|ADN|||"
	["PUJJONIRU*"]="Lenovo Chromebook 2-in-1 14ITN10|ADN|||"
	["PUJJOTEEN(15W)-CZPM*"]="Lenovo 14e Chromebook Gen 3|ADN|pujjo||"
	["PUJJOTEEN-CZPM*"]="Lenovo 14e Chromebook Gen 3|ADN|pujjo||"
	["PUJJOTEEN(15W)-KCBW*"]="Lenovo 14e Chromebook Gen 3|ADN|pujjo||"
	["PUJJOTEEN-KCBW*"]="Lenovo 14e Chromebook Gen 3|ADN|pujjo||"
	["PUJJOTEEN-JQII*"]="Lenovo 14e Chromebook Gen 3 CB 5|ADN|pujjo||"
	["PUJJOTEEN-JQLW*"]="Lenovo IdeaPad Slim 3i Chromebook Plus|ADN|pujjo||"
	["PUJJOTEEN*"]="Lenovo IdeaPad Slim 3i or 14e Gen 3 Chromebook|ADN|pujjo||"
	["PUJJOTEEN15W*"]="Lenovo 14e Chromebook Gen 3|ADN|pujjo||"
	["PUJJO*"]="Lenovo 500e Yoga/Flex 3i Chromebook|ADN|||"
	["QUANDISO2*"]="CTL Chromebook NL73 Gen 2|ADN|quandiso||"
	["QUANDISO3602*"]="CTL Chromebook NL73T Gen 2|ADN|quandiso||"
	["QUANDISO360*"]="CTL Chromebook NL73T|ADN|quandiso||"
	["QUANDISO360-UIST*"]="Mouse Chromebook U1-DAU01GY-A|ADN|quandiso||"
	["QUANDISO360-VGVL*"]="Edxis Chromebook 11 / Mouse Chromebook U1|ADN|quandiso||"
	["QUANDISO360*"]="Edxis Chromebook 11 (S30-X25)|ADN|quandiso||"
	["QUANDISO-ISWD*"]="Edxis Chromebook 11 (S30-C25)|ADN|quandiso||"
	["QUANDISO-REAV*"]="CTL Chromebook NL73 / Edxis Chromebook 11|ADN|quandiso||"
	["QUANDISO*"]="CTL Chromebook NL73|ADN|||"
	["RIVEN*"]="Acer Chromebook Spin 511|ADN|||"
	["RORIC*"]="Acer Chromebook Plus 514|ADN|rull||"
	["RUDRIKS*"]="Acer Chromebook Spin 512|ADN|riven||"
	["RUKE*"]="Acer Chromebook 315|ADN|rull||"
	["RULL*"]="Acer Chromebook 514 C937|ADN|||"
	["RYNAX*"]="Acer Chromebook 511|ADN|riven||"
	["SUNDANCE*"]="NEC Chromebook Y4|ADN|||"
	["TELIKS360*"]="ASUS Chromebook CR11 Flip (CR1104FTA)|ADN|teliks||"
	["TELIKS*"]="ASUS Chromebook CR11 (CR1104CTA)|ADN|||"
	["TELITH*"]="ASUS Chromebook CX15 (CX1505CTA)|ADN|||"
	["TELTIC*"]="ASUS Chromebook CX14 (CX1405CTA)|ADN|telith||"
	["ULDREN360*"]="Dell Chromebook 3120 2-in-1|ADN|uldren||"
	["ULDREN*"]="Dell Chromebook 3120|ADN|||"
	["XIVU360*"]="Asus Chromebook CR11 [CR1102F]|ADN|xivu||"
	["XIVU*"]="Asus Chromebook CR11 [CR1102C]|ADN|||"
	["YAHIKO*"]="HP Chromebook 14a-nf0xxx|ADN|yaviks||"
	["YAVIJO*"]="HP Fortis 14 G11 Chromebook|ADN|yavilla||"
	["YAVIKS*"]="HP Chromebook 15.6|ADN|||"
	["YAVILLA*"]="HP Fortis 11 G10 Chromebook|ADN|||"
	["YAVILLY*"]="HP Fortis x360 11 G5 Chromebook|ADN|yavilla||"

	# MTL devices - Intel Meteorlake
	["KANIX*"]="Acer Chromebook Plus 714|MTL|||"
	["KARIS*"]="Acer Chromebook Plus Spin 714|MTL|||"
	["SCREEBO*"]="ASUS ExpertBook CX54 Chromebook Plus (CX5403)|MTL|||"

	## AMD Devices

	# STR devices - AMD StoneyRidge
	["ALEENA*"]="Acer Chromebook 315 (CB315-2H)|STR|||"
	["BARLA*"]="HP Chromebook 11A G6 EE|STR|careena||"
	["CAREENA*"]="HP Chromebook 14|STR|||"
	["KASUMI360*"]="Acer Chromebook Spin 311 (R721T)|STR|aleena||"
	["KASUMI*"]="Acer Chromebook 311 (C721)|STR|aleena||"
	["LIARA*"]="Lenovo 14e Chromebook|STR|||"
	["TREEYA-QCDF*"]="Lenovo IdeaPad 3 Chromebook|STR|||"
	["TREEYA360-TZIV*"]="NEC Chromebook Y1 Gen2A|STR|treeya||"
	["TREEYA360*"]="Lenovo 300e Gen 2 AST|STR|treeya||"
	["TREEYA*"]="Lenovo 100e Gen 2 AST|STR|||"

	# PCO devices - AMD Picasso
	["BERKNIP*"]="HP Chromebook 14b|PCO|||"
	["DIRINBOZ*"]="HP Chromebook 14a|PCO|||"
	["EZKINIL*"]="Acer Chromebook Spin 514|PCO|||"
	["GUMBOZ*"]="HP Chromebook x360 14a-cb0|PCO|||"
	["JELBOZ360*"]="ASUS Chromebook Flip CM1 (CM1400)|PCO|shuboz||"
	["MORPHIUS*"]="Lenovo ThinkPad C13 Yoga Chromebook|PCO|||"
	["VILBOZ*"]="Lenovo 100e or 14e Chromebook / NEC Chromebook Y1|PCO|vilboz||"
	["WOOMAX*"]="ASUS Chromebook Flip CM5|PCO|||"

	# CZN devices - AMD Cezanne
	["DEWATT*"]="Acer Chromebook Spin 514 [CP514-3H]|CZN|||"
	["NIPPERKIN*"]="HP Elite c645 G2 Chromebook|CZN|||"

	# MDN devices - AMD Mendocino
	["CRYSTALDRIFT*"]="SPC Chromebook V1|MDN|||"
	["FROSTFLOW*"]="ASUS Chromebook CM34 Flip|MDN|||"
	["MARKARTH*"]="Acer Chromebook Plus 514|MDN|||"
	["SKYRIM*"]="Skyrim Baseboard Chromebook|MDN|||"
	["WHITERUN*"]="Dell Latitude 3445 Chromebook|MDN|winterhold||"


	## Non-ChromeOS devices
	["LIBREM13V1"]="Purism Librem 13 v1|BDW|librem13v1||"
	["LIBREM15V2"]="Purism Librem 15 v2|BDW|librem15v2||"
	["LIBREM13V2"]="Purism Librem 13 v2|SKL|||"
	["LIBREM13V3"]="Purism Librem 13 v3|SKL|librem13v2||"
	["LIBREM15V3"]="Purism Librem 15 v3|SKL|||"
	["LIBREM_13_V2"]="Purism Librem 13 v2|SKL|librem13v2||"
	["LIBREM_13_V3"]="Purism Librem 13 v3|SKL|librem13v2||"
	["LIBREM_15_V3"]="Purism Librem 15 v3|SKL|librem15v3||"
	["LIBREM13V4"]="Purism Librem 13 v4|KBL|||"
	["LIBREM15V4"]="Purism Librem 15 v4|KBL|||"
	["LIBREM_13_V4"]="Purism Librem 13 v4|KBL|librem13v4||"
	["LIBREM_15_V4"]="Purism Librem 15 v4|KBL|librem15v4||"
	["LIBREM_MINI"]="Purism Librem Mini|WHL|librem_mini||"
	["LIBREM_14"]="Purism Librem 14|CML|librem_14||"
	["LIBREM_MINI_V2"]="Purism Librem Mini v2|CML|librem_mini_v2||"
)
